### ISSUE TITLE
Publish the Helm-Chart

### ISSUE THREAD

**Issue by tibuntu** [derJD/cert-manager-webhook-autodns#1]
Hey there!

We started using this webhook for our Cert-Manager and it works like a charm.

Would it be possible to publish to Helm-Chart (e.g. via Github Pages: https://helm.sh/docs/topics/chart_repository/#github-pages-example) so that we can use it without forking this repo / deploying it manually from local?

If I can assist with that, just let me know!

**Comment by till** [comment]
@tibuntu I tried to get in touch with the author myself, if you still need this, send a PR here: https://github.com/hostwithquantum/cert-manager-webhook-autodns/. We are gonna maintain it.
